[tool.poetry]
name = "sorter"
version = "0.1.0"
description = "This application sort files"
authors = ["Wargoth"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
transliterate = "^1.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
